on:
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: "swift:5.3"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: swift test --enable-test-discovery --sanitize=thread
